namespace: webapps

mysql:
  image: mysql:8
  rootPassword: Test@123
  database: bankappdb
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"
  pvcSize: 5Gi

bankapp:
  image: suresh3/bankapp:v13
  replicas: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilization: 70

  ingressController:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  replicaCount: 2
  image: k8s.gcr.io/ingress-nginx/controller:v1.1.1

  service:
    name: ingress-nginx
    type: LoadBalancer
global:
  namespace: bank-app

storageClass:
  name: standard
  provisioner: kubernetes.io/aws-ebs
  parameters:
    type: gp2
  reclaimPolicy: Retain
  volumeBindingMode: WaitForFirstConsumer


domain: www.sureshapp.co
tlsSecret: sureshapp-co-tls

email: bsuresh5453@gmail.com
